export interface EmojiData {
  emoji: string;
  name: string;
  category: string;
  keywords: string[];
}

export const EMOJI_CATEGORIES = [
  "Recentes",
  "Sorrisos & Pessoas",
  "Animais & Natureza",
  "Comida & Bebida",
  "Atividades",
  "Viagem & Lugares",
  "Objetos",
  "Símbolos",
];

export const ALL_EMOJIS: EmojiData[] = [
  {
    emoji: "😀",
    name: "Riso",
    category: "Sorrisos & Pessoas",
    keywords: ["smile", "happy", "feliz", "alegre"],
  },
  {
    emoji: "😃",
    name: "Riso aberto",
    category: "Sorrisos & Pessoas",
    keywords: ["smile", "happy", "feliz"],
  },
  {
    emoji: "😄",
    name: "Riso olhos fechados",
    category: "Sorrisos & Pessoas",
    keywords: ["smile", "happy", "feliz"],
  },
  {
    emoji: "😁",
    name: "Riso radiante",
    category: "Sorrisos & Pessoas",
    keywords: ["smile", "grin", "feliz"],
  },
  {
    emoji: "😆",
    name: "Riso apertado",
    category: "Sorrisos & Pessoas",
    keywords: ["smile", "laugh", "engraçado"],
  },
  {
    emoji: "😅",
    name: "Riso com suor",
    category: "Sorrisos & Pessoas",
    keywords: ["smile", "sweat", "alívio"],
  },
  {
    emoji: "🤣",
    name: "Rolando de rir",
    category: "Sorrisos & Pessoas",
    keywords: ["laugh", "funny", "engraçado", "lol"],
  },
  {
    emoji: "😂",
    name: "Lágrimas de alegria",
    category: "Sorrisos & Pessoas",
    keywords: ["laugh", "happy", "feliz", "lol"],
  },
  {
    emoji: "🙂",
    name: "Sorriso leve",
    category: "Sorrisos & Pessoas",
    keywords: ["smile", "happy", "feliz"],
  },
  {
    emoji: "🙃",
    name: "Rosto de cabeça para baixo",
    category: "Sorrisos & Pessoas",
    keywords: ["upside down", "silly", "tolo"],
  },
  {
    emoji: "😉",
    name: "Piscada",
    category: "Sorrisos & Pessoas",
    keywords: ["wink", "piscada"],
  },
  {
    emoji: "😊",
    name: "Rosto sorridente bochechas rosadas",
    category: "Sorrisos & Pessoas",
    keywords: ["smile", "blush", "feliz"],
  },
  {
    emoji: "😇",
    name: "Anjo",
    category: "Sorrisos & Pessoas",
    keywords: ["angel", "halo", "inocente"],
  },
  {
    emoji: "🥰",
    name: "Corações",
    category: "Sorrisos & Pessoas",
    keywords: ["love", "amor", "apaixonado"],
  },
  {
    emoji: "😍",
    name: "Olhos de coração",
    category: "Sorrisos & Pessoas",
    keywords: ["love", "heart eyes", "amor"],
  },
  {
    emoji: "🤩",
    name: "Estrela nos olhos",
    category: "Sorrisos & Pessoas",
    keywords: ["star struck", "wow", "incrível"],
  },
  {
    emoji: "😘",
    name: "Beijo",
    category: "Sorrisos & Pessoas",
    keywords: ["kiss", "love", "amor", "beijo"],
  },
  {
    emoji: "😋",
    name: "Língua",
    category: "Sorrisos & Pessoas",
    keywords: ["yum", "delicious", "delícia", "fome"],
  },
  {
    emoji: "😛",
    name: "Língua de fora",
    category: "Sorrisos & Pessoas",
    keywords: ["tongue", "silly", "tolo"],
  },
  {
    emoji: "😜",
    name: "Língua e piscada",
    category: "Sorrisos & Pessoas",
    keywords: ["tongue", "wink", "piscada"],
  },
  {
    emoji: "🤪",
    name: "Rosto doido",
    category: "Sorrisos & Pessoas",
    keywords: ["crazy", "doido", "zany"],
  },
  {
    emoji: "🤑",
    name: "Dinheiro",
    category: "Sorrisos & Pessoas",
    keywords: ["money", "rich", "rico", "dinheiro"],
  },
  {
    emoji: "🤗",
    name: "Abraço",
    category: "Sorrisos & Pessoas",
    keywords: ["hug", "abraço"],
  },
  {
    emoji: "🤭",
    name: "Mão na boca",
    category: "Sorrisos & Pessoas",
    keywords: ["hand over mouth", "shh", "ops"],
  },
  {
    emoji: "🤫",
    name: "Silêncio",
    category: "Sorrisos & Pessoas",
    keywords: ["shush", "quiet", "silêncio"],
  },
  {
    emoji: "🤔",
    name: "Pensativo",
    category: "Sorrisos & Pessoas",
    keywords: ["thinking", "hmm", "pensar"],
  },
  {
    emoji: "🤐",
    name: "Boca fechada",
    category: "Sorrisos & Pessoas",
    keywords: ["zipper", "secret", "segredo"],
  },
  {
    emoji: "🤨",
    name: "Sobrancelha levantada",
    category: "Sorrisos & Pessoas",
    keywords: ["raised eyebrow", "doubt", "dúvida"],
  },
  {
    emoji: "😐",
    name: "Neutro",
    category: "Sorrisos & Pessoas",
    keywords: ["neutral", "meh"],
  },
  {
    emoji: "😑",
    name: "Sem expressão",
    category: "Sorrisos & Pessoas",
    keywords: ["expressionless", "bored", "tedio"],
  },
  {
    emoji: "😶",
    name: "Sem boca",
    category: "Sorrisos & Pessoas",
    keywords: ["no mouth", "silence"],
  },
  {
    emoji: "😏",
    name: "Sorriso maroto",
    category: "Sorrisos & Pessoas",
    keywords: ["smirk", "sassy"],
  },
  {
    emoji: "😒",
    name: "Insatisfeito",
    category: "Sorrisos & Pessoas",
    keywords: ["unamused", "bored", "chato"],
  },
  {
    emoji: "🙄",
    name: "Olhos revirando",
    category: "Sorrisos & Pessoas",
    keywords: ["rolling eyes", "annoyed", "irritado"],
  },
  {
    emoji: "😬",
    name: "Careta",
    category: "Sorrisos & Pessoas",
    keywords: ["grimacing", "nervous", "nervoso"],
  },
  {
    emoji: "🤥",
    name: "Mentiroso",
    category: "Sorrisos & Pessoas",
    keywords: ["lying", "pinocchio", "mentira"],
  },
  {
    emoji: "😌",
    name: "Aliviado",
    category: "Sorrisos & Pessoas",
    keywords: ["relieved", "calm", "calmo"],
  },
  {
    emoji: "😔",
    name: "Pensativo triste",
    category: "Sorrisos & Pessoas",
    keywords: ["pensive", "sad", "triste"],
  },
  {
    emoji: "😪",
    name: "Sono",
    category: "Sorrisos & Pessoas",
    keywords: ["sleepy", "tired", "sono"],
  },
  {
    emoji: "🤤",
    name: "Babando",
    category: "Sorrisos & Pessoas",
    keywords: ["drooling", "delicious"],
  },
  {
    emoji: "😴",
    name: "Dormindo",
    category: "Sorrisos & Pessoas",
    keywords: ["sleeping", "zzz", "dormir"],
  },
  {
    emoji: "😷",
    name: "Máscara",
    category: "Sorrisos & Pessoas",
    keywords: ["mask", "sick", "doente"],
  },
  {
    emoji: "🤒",
    name: "Termômetro",
    category: "Sorrisos & Pessoas",
    keywords: ["fever", "sick", "febre"],
  },
  {
    emoji: "🤕",
    name: "Bandagem",
    category: "Sorrisos & Pessoas",
    keywords: ["injured", "hurt", "machucado"],
  },
  {
    emoji: "🤢",
    name: "Nausea",
    category: "Sorrisos & Pessoas",
    keywords: ["nauseated", "sick", "enjoado"],
  },
  {
    emoji: "🤮",
    name: "Vomitando",
    category: "Sorrisos & Pessoas",
    keywords: ["vomit", "sick", "vômito"],
  },
  {
    emoji: "🤧",
    name: "Espirro",
    category: "Sorrisos & Pessoas",
    keywords: ["sneezing", "cold", "gripe"],
  },
  {
    emoji: "🥵",
    name: "Calor",
    category: "Sorrisos & Pessoas",
    keywords: ["hot", "heat", "calor"],
  },
  {
    emoji: "🥶",
    name: "Frio",
    category: "Sorrisos & Pessoas",
    keywords: ["cold", "freezing", "frio"],
  },
  {
    emoji: "🥴",
    name: "Tonto",
    category: "Sorrisos & Pessoas",
    keywords: ["woozy", "dizzy", "tonto"],
  },
  {
    emoji: "😵",
    name: "Atordoado",
    category: "Sorrisos & Pessoas",
    keywords: ["dizzy", "dead"],
  },
  {
    emoji: "🤯",
    name: "Explosão mental",
    category: "Sorrisos & Pessoas",
    keywords: ["mind blown", "shock", "choque"],
  },
  {
    emoji: "🤠",
    name: "Cowboy",
    category: "Sorrisos & Pessoas",
    keywords: ["cowboy", "hat", "chapeu"],
  },
  {
    emoji: "🥳",
    name: "Festa",
    category: "Sorrisos & Pessoas",
    keywords: ["party", "celebrate", "festa"],
  },
  {
    emoji: "😎",
    name: "Óculos escuros",
    category: "Sorrisos & Pessoas",
    keywords: ["cool", "sunglasses", "estilo"],
  },
  {
    emoji: "🤓",
    name: "Nerd",
    category: "Sorrisos & Pessoas",
    keywords: ["nerd", "glasses"],
  },
  {
    emoji: "🧐",
    name: "Monóculo",
    category: "Sorrisos & Pessoas",
    keywords: ["monocle", "smart"],
  },
  {
    emoji: "😕",
    name: "Confuso",
    category: "Sorrisos & Pessoas",
    keywords: ["confused", "meh"],
  },
  {
    emoji: "😟",
    name: "Preocupado",
    category: "Sorrisos & Pessoas",
    keywords: ["worried", "sad"],
  },
  {
    emoji: "🙁",
    name: "Triste leve",
    category: "Sorrisos & Pessoas",
    keywords: ["frown", "sad"],
  },
  {
    emoji: "😮",
    name: "Surpreso",
    category: "Sorrisos & Pessoas",
    keywords: ["surprise", "wow"],
  },
  {
    emoji: "😲",
    name: "Espantado",
    category: "Sorrisos & Pessoas",
    keywords: ["astonished", "shock"],
  },
  {
    emoji: "😳",
    name: "Envergonhado",
    category: "Sorrisos & Pessoas",
    keywords: ["blush", "flushed", "vergonha"],
  },
  {
    emoji: "🥺",
    name: "Pedinte",
    category: "Sorrisos & Pessoas",
    keywords: ["pleading", "begging", "por favor"],
  },
  {
    emoji: "😦",
    name: "Boca aberta",
    category: "Sorrisos & Pessoas",
    keywords: ["frown", "shock"],
  },
  {
    emoji: "😨",
    name: "Amedrontado",
    category: "Sorrisos & Pessoas",
    keywords: ["fear", "scared", "medo"],
  },
  {
    emoji: "😰",
    name: "Ansioso com suor",
    category: "Sorrisos & Pessoas",
    keywords: ["anxious", "sweat", "nervoso"],
  },
  {
    emoji: "😥",
    name: "Triste mas aliviado",
    category: "Sorrisos & Pessoas",
    keywords: ["sad", "relieved", "triste"],
  },
  {
    emoji: "😢",
    name: "Chorando",
    category: "Sorrisos & Pessoas",
    keywords: ["cry", "sad", "lágrima"],
  },
  {
    emoji: "😭",
    name: "Chorando muito",
    category: "Sorrisos & Pessoas",
    keywords: ["loudly crying", "sad", "triste"],
  },
  {
    emoji: "😱",
    name: "Gritando de medo",
    category: "Sorrisos & Pessoas",
    keywords: ["scream", "fear", "medo"],
  },
  {
    emoji: "😖",
    name: "Perplexo",
    category: "Sorrisos & Pessoas",
    keywords: ["confounded", "struggle"],
  },
  {
    emoji: "😞",
    name: "Desapontado",
    category: "Sorrisos & Pessoas",
    keywords: ["disappointed", "sad"],
  },
  {
    emoji: "😓",
    name: "Suor frio",
    category: "Sorrisos & Pessoas",
    keywords: ["sweat", "sad", "triste"],
  },
  {
    emoji: "😩",
    name: "Exausto",
    category: "Sorrisos & Pessoas",
    keywords: ["weary", "tired", "cansado"],
  },
  {
    emoji: "😫",
    name: "Cansado",
    category: "Sorrisos & Pessoas",
    keywords: ["tired", "weary", "cansado"],
  },
  {
    emoji: "🥱",
    name: "Bocejando",
    category: "Sorrisos & Pessoas",
    keywords: ["yawning", "tired", "sono"],
  },
  {
    emoji: "😤",
    name: "Triunfo",
    category: "Sorrisos & Pessoas",
    keywords: ["triumph", "angry", "bravo"],
  },
  {
    emoji: "😡",
    name: "Irritado",
    category: "Sorrisos & Pessoas",
    keywords: ["pouting", "angry", "bravo"],
  },
  {
    emoji: "😠",
    name: "Bravo",
    category: "Sorrisos & Pessoas",
    keywords: ["angry", "mad", "bravo"],
  },
  {
    emoji: "🤬",
    name: "Xingando",
    category: "Sorrisos & Pessoas",
    keywords: ["cursing", "angry", "raiva"],
  },
  {
    emoji: "😈",
    name: "Diabinho sorridente",
    category: "Sorrisos & Pessoas",
    keywords: ["devil", "evil", "mal"],
  },
  {
    emoji: "💀",
    name: "Caveira",
    category: "Sorrisos & Pessoas",
    keywords: ["skull", "dead", "morte"],
  },
  {
    emoji: "💩",
    name: "Cocô",
    category: "Sorrisos & Pessoas",
    keywords: ["poop", "funny", "engraçado"],
  },
  {
    emoji: "🤡",
    name: "Palhaço",
    category: "Sorrisos & Pessoas",
    keywords: ["clown", "funny"],
  },
  {
    emoji: "👻",
    name: "Fantasma",
    category: "Sorrisos & Pessoas",
    keywords: ["ghost", "spooky", "fantasma"],
  },
  {
    emoji: "👽",
    name: "Alien",
    category: "Sorrisos & Pessoas",
    keywords: ["alien", "ufo"],
  },
  {
    emoji: "👾",
    name: "Monstro de jogo",
    category: "Sorrisos & Pessoas",
    keywords: ["alien monster", "game", "jogo"],
  },
  {
    emoji: "🤖",
    name: "Robô",
    category: "Sorrisos & Pessoas",
    keywords: ["robot", "tech"],
  },
  {
    emoji: "😺",
    name: "Gato sorridente",
    category: "Sorrisos & Pessoas",
    keywords: ["cat", "happy", "gato"],
  },
  {
    emoji: "😻",
    name: "Gato corações",
    category: "Sorrisos & Pessoas",
    keywords: ["cat", "love", "gato"],
  },
  {
    emoji: "👋",
    name: "Aceno",
    category: "Sorrisos & Pessoas",
    keywords: ["wave", "hello", "oi", "tchau"],
  },
  {
    emoji: "🤚",
    name: "Costas da mão",
    category: "Sorrisos & Pessoas",
    keywords: ["raised back of hand"],
  },
  {
    emoji: "🖐",
    name: "Mão aberta",
    category: "Sorrisos & Pessoas",
    keywords: ["hand", "fingers"],
  },
  {
    emoji: "✋",
    name: "Mão levantada",
    category: "Sorrisos & Pessoas",
    keywords: ["hand", "stop", "pare"],
  },
  {
    emoji: "👌",
    name: "Ok",
    category: "Sorrisos & Pessoas",
    keywords: ["ok", "perfect", "perfeito"],
  },
  {
    emoji: "🤌",
    name: "Mão em pinça",
    category: "Sorrisos & Pessoas",
    keywords: ["pinched fingers", "italian"],
  },
  {
    emoji: "✌️",
    name: "Paz",
    category: "Sorrisos & Pessoas",
    keywords: ["peace", "victory", "vitória"],
  },
  {
    emoji: "🤞",
    name: "Dedos cruzados",
    category: "Sorrisos & Pessoas",
    keywords: ["crossed fingers", "luck", "sorte"],
  },
  {
    emoji: "🤟",
    name: "Te amo",
    category: "Sorrisos & Pessoas",
    keywords: ["love you", "rock"],
  },
  {
    emoji: "🤘",
    name: "Rock",
    category: "Sorrisos & Pessoas",
    keywords: ["rock on", "metal"],
  },
  {
    emoji: "🤙",
    name: "Me liga",
    category: "Sorrisos & Pessoas",
    keywords: ["call me", "surf"],
  },
  {
    emoji: "👍",
    name: "Joinha",
    category: "Sorrisos & Pessoas",
    keywords: ["thumbs up", "like", "gostei"],
  },
  {
    emoji: "👎",
    name: "Deslike",
    category: "Sorrisos & Pessoas",
    keywords: ["thumbs down", "dislike"],
  },
  {
    emoji: "👊",
    name: "Soco",
    category: "Sorrisos & Pessoas",
    keywords: ["fist", "punch"],
  },
  {
    emoji: "👏",
    name: "Aplausos",
    category: "Sorrisos & Pessoas",
    keywords: ["clap", "bravo", "parabéns"],
  },
  {
    emoji: "🙌",
    name: "Mãos para cima",
    category: "Sorrisos & Pessoas",
    keywords: ["celebration", "hands up"],
  },
  {
    emoji: "🤝",
    name: "Aperto de mãos",
    category: "Sorrisos & Pessoas",
    keywords: ["handshake", "agreement", "acordo"],
  },
  {
    emoji: "🙏",
    name: "Mãos juntas",
    category: "Sorrisos & Pessoas",
    keywords: ["pray", "please", "obrigado", "por favor"],
  },
  {
    emoji: "💅",
    name: "Unhas",
    category: "Sorrisos & Pessoas",
    keywords: ["nails", "polish", "manicure"],
  },
  {
    emoji: "💪",
    name: "Bíceps",
    category: "Sorrisos & Pessoas",
    keywords: ["muscle", "strong", "força"],
  },
  {
    emoji: "🧠",
    name: "Cérebro",
    category: "Sorrisos & Pessoas",
    keywords: ["brain", "smart", "inteligente"],
  },
  {
    emoji: "👀",
    name: "Olhos",
    category: "Sorrisos & Pessoas",
    keywords: ["eyes", "look", "olhar"],
  },
  {
    emoji: "👶",
    name: "Bebê",
    category: "Sorrisos & Pessoas",
    keywords: ["baby", "child", "criança"],
  },
  {
    emoji: "👦",
    name: "Menino",
    category: "Sorrisos & Pessoas",
    keywords: ["boy", "child"],
  },
  {
    emoji: "👧",
    name: "Menina",
    category: "Sorrisos & Pessoas",
    keywords: ["girl", "child"],
  },
  {
    emoji: "👨",
    name: "Homem",
    category: "Sorrisos & Pessoas",
    keywords: ["man", "adult"],
  },
  {
    emoji: "👩",
    name: "Mulher",
    category: "Sorrisos & Pessoas",
    keywords: ["woman", "adult"],
  },
  {
    emoji: "👴",
    name: "Vovô",
    category: "Sorrisos & Pessoas",
    keywords: ["old man", "grandpa"],
  },
  {
    emoji: "👵",
    name: "Vovó",
    category: "Sorrisos & Pessoas",
    keywords: ["old woman", "grandma"],
  },

  // Animais & Natureza
  {
    emoji: "🐶",
    name: "Cachorro",
    category: "Animais & Natureza",
    keywords: ["dog", "puppy", "pet", "animal", "cão"],
  },
  {
    emoji: "🐱",
    name: "Gato",
    category: "Animais & Natureza",
    keywords: ["cat", "kitten", "pet", "animal", "gato"],
  },
  {
    emoji: "🐭",
    name: "Rato",
    category: "Animais & Natureza",
    keywords: ["mouse", "animal"],
  },
  {
    emoji: "🐹",
    name: "Hamster",
    category: "Animais & Natureza",
    keywords: ["hamster", "animal"],
  },
  {
    emoji: "🐰",
    name: "Coelho",
    category: "Animais & Natureza",
    keywords: ["rabbit", "bunny", "animal", "coelho"],
  },
  {
    emoji: "🦊",
    name: "Raposa",
    category: "Animais & Natureza",
    keywords: ["fox", "animal"],
  },
  {
    emoji: "🐻",
    name: "Urso",
    category: "Animais & Natureza",
    keywords: ["bear", "animal"],
  },
  {
    emoji: "🐼",
    name: "Panda",
    category: "Animais & Natureza",
    keywords: ["panda", "animal"],
  },
  {
    emoji: "🐨",
    name: "Coala",
    category: "Animais & Natureza",
    keywords: ["koala", "animal"],
  },
  {
    emoji: "🐯",
    name: "Tigre",
    category: "Animais & Natureza",
    keywords: ["tiger", "animal"],
  },
  {
    emoji: "🦁",
    name: "Leão",
    category: "Animais & Natureza",
    keywords: ["lion", "animal"],
  },
  {
    emoji: "🐮",
    name: "Vaca",
    category: "Animais & Natureza",
    keywords: ["cow", "animal"],
  },
  {
    emoji: "🐷",
    name: "Porco",
    category: "Animais & Natureza",
    keywords: ["pig", "animal"],
  },
  {
    emoji: "🐸",
    name: "Sapo",
    category: "Animais & Natureza",
    keywords: ["frog", "animal"],
  },
  {
    emoji: "🐵",
    name: "Macaco",
    category: "Animais & Natureza",
    keywords: ["monkey", "animal"],
  },
  {
    emoji: "🐔",
    name: "Galinha",
    category: "Animais & Natureza",
    keywords: ["chicken", "animal"],
  },
  {
    emoji: "🐧",
    name: "Pinguim",
    category: "Animais & Natureza",
    keywords: ["penguin", "animal"],
  },
  {
    emoji: "🐦",
    name: "Pássaro",
    category: "Animais & Natureza",
    keywords: ["bird", "animal"],
  },
  {
    emoji: "🐤",
    name: "Pinto",
    category: "Animais & Natureza",
    keywords: ["chick", "animal"],
  },
  {
    emoji: "🦆",
    name: "Pato",
    category: "Animais & Natureza",
    keywords: ["duck", "animal"],
  },
  {
    emoji: "🦅",
    name: "Águia",
    category: "Animais & Natureza",
    keywords: ["eagle", "animal"],
  },
  {
    emoji: "🦉",
    name: "Coruja",
    category: "Animais & Natureza",
    keywords: ["owl", "animal"],
  },
  {
    emoji: "🦇",
    name: "Morcego",
    category: "Animais & Natureza",
    keywords: ["bat", "animal"],
  },
  {
    emoji: "🐺",
    name: "Lobo",
    category: "Animais & Natureza",
    keywords: ["wolf", "animal"],
  },
  {
    emoji: "🐴",
    name: "Cavalo",
    category: "Animais & Natureza",
    keywords: ["horse", "animal"],
  },
  {
    emoji: "🦄",
    name: "Unicórnio",
    category: "Animais & Natureza",
    keywords: ["unicorn", "animal", "fantasy"],
  },
  {
    emoji: "🐝",
    name: "Abelha",
    category: "Animais & Natureza",
    keywords: ["bee", "insect"],
  },
  {
    emoji: "🦋",
    name: "Borboleta",
    category: "Animais & Natureza",
    keywords: ["butterfly", "insect"],
  },
  {
    emoji: "🐌",
    name: "Caracol",
    category: "Animais & Natureza",
    keywords: ["snail", "animal"],
  },
  {
    emoji: "🐞",
    name: "Joaninha",
    category: "Animais & Natureza",
    keywords: ["ladybug", "insect"],
  },
  {
    emoji: "🐢",
    name: "Tartaruga",
    category: "Animais & Natureza",
    keywords: ["turtle", "animal"],
  },
  {
    emoji: "🐍",
    name: "Cobra",
    category: "Animais & Natureza",
    keywords: ["snake", "animal"],
  },
  {
    emoji: "🦖",
    name: "T-Rex",
    category: "Animais & Natureza",
    keywords: ["dino", "dinosaur"],
  },
  {
    emoji: "🐙",
    name: "Polvo",
    category: "Animais & Natureza",
    keywords: ["octopus", "animal", "sea"],
  },
  {
    emoji: "🐬",
    name: "Golfinho",
    category: "Animais & Natureza",
    keywords: ["dolphin", "sea"],
  },
  {
    emoji: "🐳",
    name: "Baleia",
    category: "Animais & Natureza",
    keywords: ["whale", "sea"],
  },
  {
    emoji: "🦈",
    name: "Tubarão",
    category: "Animais & Natureza",
    keywords: ["shark", "sea"],
  },
  {
    emoji: "🐊",
    name: "Jacaré",
    category: "Animais & Natureza",
    keywords: ["crocodile", "animal"],
  },
  {
    emoji: "🦓",
    name: "Zebra",
    category: "Animais & Natureza",
    keywords: ["zebra"],
  },
  {
    emoji: "🐘",
    name: "Elefante",
    category: "Animais & Natureza",
    keywords: ["elephant"],
  },
  {
    emoji: "🦒",
    name: "Girafa",
    category: "Animais & Natureza",
    keywords: ["giraffe"],
  },
  {
    emoji: "🐖",
    name: "Porco",
    category: "Animais & Natureza",
    keywords: ["pig"],
  },
  {
    emoji: "🐑",
    name: "Ovelha",
    category: "Animais & Natureza",
    keywords: ["sheep"],
  },
  {
    emoji: "🐐",
    name: "Cabra",
    category: "Animais & Natureza",
    keywords: ["goat"],
  },
  {
    emoji: "🦌",
    name: "Cervo",
    category: "Animais & Natureza",
    keywords: ["deer"],
  },
  {
    emoji: "🐇",
    name: "Coelho",
    category: "Animais & Natureza",
    keywords: ["rabbit"],
  },
  {
    emoji: "🐿",
    name: "Esquilo",
    category: "Animais & Natureza",
    keywords: ["chipmunk"],
  },
  {
    emoji: "🐾",
    name: "Patas",
    category: "Animais & Natureza",
    keywords: ["paws", "tracks"],
  },
  {
    emoji: "🌵",
    name: "Cacto",
    category: "Animais & Natureza",
    keywords: ["cactus", "nature"],
  },
  {
    emoji: "🎄",
    name: "Árvore de Natal",
    category: "Animais & Natureza",
    keywords: ["christmas tree"],
  },
  {
    emoji: "🌲",
    name: "Pinheiro",
    category: "Animais & Natureza",
    keywords: ["evergreen tree"],
  },
  {
    emoji: "🌳",
    name: "Árvore",
    category: "Animais & Natureza",
    keywords: ["deciduous tree"],
  },
  {
    emoji: "🌴",
    name: "Palmeira",
    category: "Animais & Natureza",
    keywords: ["palm tree"],
  },
  {
    emoji: "🌱",
    name: "Broto",
    category: "Animais & Natureza",
    keywords: ["seedling", "nature", "planta"],
  },
  {
    emoji: "🌿",
    name: "Erva",
    category: "Animais & Natureza",
    keywords: ["herb", "nature"],
  },
  {
    emoji: "☘️",
    name: "Trevo",
    category: "Animais & Natureza",
    keywords: ["shamrock", "luck"],
  },
  {
    emoji: "🍀",
    name: "Trevo de quatro folhas",
    category: "Animais & Natureza",
    keywords: ["four leaf clover", "luck", "sorte"],
  },
  {
    emoji: "🍃",
    name: "Folhas ao vento",
    category: "Animais & Natureza",
    keywords: ["leaf", "nature"],
  },
  {
    emoji: "🍂",
    name: "Folhas caídas",
    category: "Animais & Natureza",
    keywords: ["fallen leaf", "autumn", "outono"],
  },
  {
    emoji: "🍁",
    name: "Folha de bordo",
    category: "Animais & Natureza",
    keywords: ["maple leaf", "autumn"],
  },
  {
    emoji: "🍄",
    name: "Cogumelo",
    category: "Animais & Natureza",
    keywords: ["mushroom", "nature"],
  },
  {
    emoji: "🐚",
    name: "Concha",
    category: "Animais & Natureza",
    keywords: ["shell", "sea"],
  },
  {
    emoji: "🌎",
    name: "Terra",
    category: "Animais & Natureza",
    keywords: ["earth", "world", "mundo"],
  },
  {
    emoji: "🌕",
    name: "Lua cheia",
    category: "Animais & Natureza",
    keywords: ["moon"],
  },
  {
    emoji: "🌙",
    name: "Lua",
    category: "Animais & Natureza",
    keywords: ["moon", "night", "noite"],
  },
  {
    emoji: "☀️",
    name: "Sol",
    category: "Animais & Natureza",
    keywords: ["sun", "day", "dia", "calor"],
  },
  {
    emoji: "🌤",
    name: "Sol entre nuvens",
    category: "Animais & Natureza",
    keywords: ["sun", "cloud"],
  },
  {
    emoji: "☁️",
    name: "Nuvem",
    category: "Animais & Natureza",
    keywords: ["cloud"],
  },
  {
    emoji: "🌧",
    name: "Chuva",
    category: "Animais & Natureza",
    keywords: ["rain", "weather", "chuva"],
  },
  {
    emoji: "⛈",
    name: "Tempestade",
    category: "Animais & Natureza",
    keywords: ["storm", "thunder"],
  },
  {
    emoji: "❄️",
    name: "Neve",
    category: "Animais & Natureza",
    keywords: ["snow", "winter", "frio", "neve"],
  },
  {
    emoji: "🔥",
    name: "Fogo",
    category: "Animais & Natureza",
    keywords: ["fire", "hot", "fogo", "quente"],
  },
  {
    emoji: "💥",
    name: "Explosão",
    category: "Animais & Natureza",
    keywords: ["collision", "boom"],
  },
  {
    emoji: "🌈",
    name: "Arco-íris",
    category: "Animais & Natureza",
    keywords: ["rainbow", "color", "arco-iris"],
  },
  {
    emoji: "🌊",
    name: "Onda",
    category: "Animais & Natureza",
    keywords: ["wave", "ocean", "mar"],
  },
  {
    emoji: "🫧",
    name: "Bolhas",
    category: "Animais & Natureza",
    keywords: ["bubbles"],
  },
  {
    emoji: "✨",
    name: "Brilhos",
    category: "Animais & Natureza",
    keywords: ["sparkles", "magic", "brilho"],
  },
  {
    emoji: "⭐",
    name: "Estrela",
    category: "Animais & Natureza",
    keywords: ["star"],
  },
  {
    emoji: "🌷",
    name: "Tulipa",
    category: "Animais & Natureza",
    keywords: ["tulip", "flower", "flor"],
  },
  {
    emoji: "🌸",
    name: "Flor de cerejeira",
    category: "Animais & Natureza",
    keywords: ["cherry blossom", "flower", "flor"],
  },
  {
    emoji: "🌹",
    name: "Rosa",
    category: "Animais & Natureza",
    keywords: ["rose", "flower", "flor"],
  },
  {
    emoji: "🌺",
    name: "Hibisco",
    category: "Animais & Natureza",
    keywords: ["hibiscus", "flower", "flor"],
  },
  {
    emoji: "🌻",
    name: "Girassol",
    category: "Animais & Natureza",
    keywords: ["sunflower", "flower", "flor"],
  },
  {
    emoji: "🌼",
    name: "Margarida",
    category: "Animais & Natureza",
    keywords: ["blossom", "flower", "flor"],
  },

  // Comida & Bebida
  {
    emoji: "🍏",
    name: "Maçã verde",
    category: "Comida & Bebida",
    keywords: ["apple", "fruit", "fruta"],
  },
  {
    emoji: "🍎",
    name: "Maçã",
    category: "Comida & Bebida",
    keywords: ["apple", "fruit", "fruta"],
  },
  {
    emoji: "🍐",
    name: "Pêra",
    category: "Comida & Bebida",
    keywords: ["pear", "fruit"],
  },
  {
    emoji: "🍊",
    name: "Laranja",
    category: "Comida & Bebida",
    keywords: ["orange", "fruit"],
  },
  {
    emoji: "🍋",
    name: "Limão",
    category: "Comida & Bebida",
    keywords: ["lemon", "fruit"],
  },
  {
    emoji: "🍌",
    name: "Banana",
    category: "Comida & Bebida",
    keywords: ["banana", "fruit"],
  },
  {
    emoji: "🍉",
    name: "Melancia",
    category: "Comida & Bebida",
    keywords: ["watermelon", "fruit", "melancia"],
  },
  {
    emoji: "🍇",
    name: "Uva",
    category: "Comida & Bebida",
    keywords: ["grapes", "fruit"],
  },
  {
    emoji: "🍓",
    name: "Morango",
    category: "Comida & Bebida",
    keywords: ["strawberry", "fruit", "morango"],
  },
  {
    emoji: "🫐",
    name: "Mirtilo",
    category: "Comida & Bebida",
    keywords: ["blueberries", "fruit"],
  },
  {
    emoji: "🍈",
    name: "Melão",
    category: "Comida & Bebida",
    keywords: ["melon", "fruit"],
  },
  {
    emoji: "🍒",
    name: "Cereja",
    category: "Comida & Bebida",
    keywords: ["cherries", "fruit"],
  },
  {
    emoji: "🍑",
    name: "Pêssego",
    category: "Comida & Bebida",
    keywords: ["peach", "fruit"],
  },
  {
    emoji: "🥭",
    name: "Manga",
    category: "Comida & Bebida",
    keywords: ["mango", "fruit"],
  },
  {
    emoji: "🍍",
    name: "Abacaxi",
    category: "Comida & Bebida",
    keywords: ["pineapple", "fruit"],
  },
  {
    emoji: "🥥",
    name: "Coco",
    category: "Comida & Bebida",
    keywords: ["coconut", "fruit"],
  },
  {
    emoji: "🥝",
    name: "Kiwi",
    category: "Comida & Bebida",
    keywords: ["kiwi", "fruit"],
  },
  {
    emoji: "🍅",
    name: "Tomate",
    category: "Comida & Bebida",
    keywords: ["tomato", "fruit"],
  },
  {
    emoji: "🍆",
    name: "Berinjela",
    category: "Comida & Bebida",
    keywords: ["eggplant", "vegetable"],
  },
  {
    emoji: "🥑",
    name: "Abacate",
    category: "Comida & Bebida",
    keywords: ["avocado", "fruit"],
  },
  {
    emoji: "🥦",
    name: "Brócolis",
    category: "Comida & Bebida",
    keywords: ["broccoli", "vegetable"],
  },
  {
    emoji: "🥬",
    name: "Folhas",
    category: "Comida & Bebida",
    keywords: ["leafy green", "vegetable"],
  },
  {
    emoji: "🥒",
    name: "Pepino",
    category: "Comida & Bebida",
    keywords: ["cucumber", "vegetable"],
  },
  {
    emoji: "🌶",
    name: "Pimenta",
    category: "Comida & Bebida",
    keywords: ["pepper", "hot"],
  },
  {
    emoji: "🌽",
    name: "Milho",
    category: "Comida & Bebida",
    keywords: ["corn", "vegetable"],
  },
  {
    emoji: "🥕",
    name: "Cenoura",
    category: "Comida & Bebida",
    keywords: ["carrot", "vegetable"],
  },
  {
    emoji: "🥔",
    name: "Batata",
    category: "Comida & Bebida",
    keywords: ["potato", "vegetable"],
  },
  {
    emoji: "🍠",
    name: "Batata doce",
    category: "Comida & Bebida",
    keywords: ["roasted sweet potato"],
  },
  {
    emoji: "🥐",
    name: "Croissant",
    category: "Comida & Bebida",
    keywords: ["croissant", "bread"],
  },
  {
    emoji: "🍞",
    name: "Pão",
    category: "Comida & Bebida",
    keywords: ["bread", "food"],
  },
  {
    emoji: "🥖",
    name: "Baguete",
    category: "Comida & Bebida",
    keywords: ["baguette", "bread"],
  },
  {
    emoji: "🥨",
    name: "Pretzel",
    category: "Comida & Bebida",
    keywords: ["pretzel"],
  },
  {
    emoji: "🧀",
    name: "Queijo",
    category: "Comida & Bebida",
    keywords: ["cheese"],
  },
  { emoji: "🥚", name: "Ovo", category: "Comida & Bebida", keywords: ["egg"] },
  {
    emoji: "🍳",
    name: "Ovo frito",
    category: "Comida & Bebida",
    keywords: ["cooking", "egg"],
  },
  {
    emoji: "🥓",
    name: "Bacon",
    category: "Comida & Bebida",
    keywords: ["bacon"],
  },
  {
    emoji: "🥩",
    name: "Carne",
    category: "Comida & Bebida",
    keywords: ["meat", "steak"],
  },
  {
    emoji: "🍗",
    name: "Frango",
    category: "Comida & Bebida",
    keywords: ["poultry leg", "chicken"],
  },
  {
    emoji: "🍖",
    name: "Carne com osso",
    category: "Comida & Bebida",
    keywords: ["meat on bone"],
  },
  {
    emoji: "🌭",
    name: "Cachorro-quente",
    category: "Comida & Bebida",
    keywords: ["hot dog"],
  },
  {
    emoji: "🍔",
    name: "Hambúrguer",
    category: "Comida & Bebida",
    keywords: ["hamburger", "burger"],
  },
  {
    emoji: "🍟",
    name: "Batata frita",
    category: "Comida & Bebida",
    keywords: ["french fries"],
  },
  {
    emoji: "🍕",
    name: "Pizza",
    category: "Comida & Bebida",
    keywords: ["pizza"],
  },
  {
    emoji: "🥪",
    name: "Sanduíche",
    category: "Comida & Bebida",
    keywords: ["sandwich"],
  },
  {
    emoji: "🌮",
    name: "Taco",
    category: "Comida & Bebida",
    keywords: ["taco"],
  },
  {
    emoji: "🌯",
    name: "Burrito",
    category: "Comida & Bebida",
    keywords: ["burrito"],
  },
  {
    emoji: "🥗",
    name: "Salada",
    category: "Comida & Bebida",
    keywords: ["green salad"],
  },
  {
    emoji: "🥘",
    name: "Paella",
    category: "Comida & Bebida",
    keywords: ["shallow pan of food"],
  },
  {
    emoji: "🍝",
    name: "Espaguete",
    category: "Comida & Bebida",
    keywords: ["spaghetti", "pasta"],
  },
  {
    emoji: "🍜",
    name: "Ramen",
    category: "Comida & Bebida",
    keywords: ["steaming bowl", "noodles"],
  },
  {
    emoji: "🍲",
    name: "Ensopado",
    category: "Comida & Bebida",
    keywords: ["pot of food"],
  },
  {
    emoji: "🍛",
    name: "Curry",
    category: "Comida & Bebida",
    keywords: ["curry rice"],
  },
  {
    emoji: "🍣",
    name: "Sushi",
    category: "Comida & Bebida",
    keywords: ["sushi"],
  },
  {
    emoji: "🍱",
    name: "Bento",
    category: "Comida & Bebida",
    keywords: ["bento box"],
  },
  {
    emoji: "🥟",
    name: "Guioza",
    category: "Comida & Bebida",
    keywords: ["dumpling"],
  },
  {
    emoji: "🍤",
    name: "Camarão frito",
    category: "Comida & Bebida",
    keywords: ["fried shrimp"],
  },
  {
    emoji: "🍙",
    name: "Bolinho de arroz",
    category: "Comida & Bebida",
    keywords: ["rice ball"],
  },
  {
    emoji: "🍚",
    name: "Arroz",
    category: "Comida & Bebida",
    keywords: ["cooked rice"],
  },
  {
    emoji: "🍘",
    name: "Biscoito de arroz",
    category: "Comida & Bebida",
    keywords: ["rice cracker"],
  },
  {
    emoji: "🍥",
    name: "Peixe prensado",
    category: "Comida & Bebida",
    keywords: ["fish cake"],
  },
  {
    emoji: "🥠",
    name: "Biscoito da sorte",
    category: "Comida & Bebida",
    keywords: ["fortune cookie"],
  },
  {
    emoji: "🍢",
    name: "Oden",
    category: "Comida & Bebida",
    keywords: ["oden"],
  },
  {
    emoji: "🍡",
    name: "Dango",
    category: "Comida & Bebida",
    keywords: ["dango"],
  },
  {
    emoji: "🍧",
    name: "Raspadinha",
    category: "Comida & Bebida",
    keywords: ["shaved ice"],
  },
  {
    emoji: "🍨",
    name: "Sorvete",
    category: "Comida & Bebida",
    keywords: ["ice cream"],
  },
  {
    emoji: "🍦",
    name: "Sorvete de casquinha",
    category: "Comida & Bebida",
    keywords: ["soft serve"],
  },
  {
    emoji: "🥧",
    name: "Torta",
    category: "Comida & Bebida",
    keywords: ["pie"],
  },
  {
    emoji: "🍰",
    name: "Bolo",
    category: "Comida & Bebida",
    keywords: ["shortcake", "cake"],
  },
  {
    emoji: "🎂",
    name: "Bolo de aniversário",
    category: "Comida & Bebida",
    keywords: ["birthday cake"],
  },
  {
    emoji: "🧁",
    name: "Cupcake",
    category: "Comida & Bebida",
    keywords: ["cupcake"],
  },
  {
    emoji: "🍮",
    name: "Pudim",
    category: "Comida & Bebida",
    keywords: ["custard"],
  },
  {
    emoji: "🍭",
    name: "Pirulito",
    category: "Comida & Bebida",
    keywords: ["lollipop"],
  },
  {
    emoji: "🍬",
    name: "Bala",
    category: "Comida & Bebida",
    keywords: ["candy"],
  },
  {
    emoji: "🍫",
    name: "Chocolate",
    category: "Comida & Bebida",
    keywords: ["chocolate bar"],
  },
  {
    emoji: "🍿",
    name: "Pipoca",
    category: "Comida & Bebida",
    keywords: ["popcorn"],
  },
  {
    emoji: "🍩",
    name: "Donut",
    category: "Comida & Bebida",
    keywords: ["doughnut"],
  },
  {
    emoji: "🍪",
    name: "Biscoito",
    category: "Comida & Bebida",
    keywords: ["cookie"],
  },
  {
    emoji: "🥜",
    name: "Amendoim",
    category: "Comida & Bebida",
    keywords: ["peanuts"],
  },
  {
    emoji: "🍯",
    name: "Mel",
    category: "Comida & Bebida",
    keywords: ["honey pot"],
  },
  {
    emoji: "🥛",
    name: "Leite",
    category: "Comida & Bebida",
    keywords: ["glass of milk"],
  },
  {
    emoji: "☕",
    name: "Café",
    category: "Comida & Bebida",
    keywords: ["coffee", "tea", "café"],
  },
  { emoji: "🍵", name: "Chá", category: "Comida & Bebida", keywords: ["tea"] },
  {
    emoji: "🥤",
    name: "Refrigerante",
    category: "Comida & Bebida",
    keywords: ["cup with straw"],
  },
  {
    emoji: "🧋",
    name: "Bubble tea",
    category: "Comida & Bebida",
    keywords: ["bubble tea"],
  },
  {
    emoji: "🧃",
    name: "Suco",
    category: "Comida & Bebida",
    keywords: ["beverage box", "juice"],
  },
  {
    emoji: "🧉",
    name: "Mate",
    category: "Comida & Bebida",
    keywords: ["mate"],
  },
  {
    emoji: "🍶",
    name: "Sake",
    category: "Comida & Bebida",
    keywords: ["sake"],
  },
  {
    emoji: "🍺",
    name: "Cerveja",
    category: "Comida & Bebida",
    keywords: ["beer", "cerveja"],
  },
  {
    emoji: "🍻",
    name: "Cervejas",
    category: "Comida & Bebida",
    keywords: ["beers", "clink"],
  },
  {
    emoji: "🥂",
    name: "Brinde",
    category: "Comida & Bebida",
    keywords: ["clinking glasses", "celebrate"],
  },
  {
    emoji: "🍷",
    name: "Vinho",
    category: "Comida & Bebida",
    keywords: ["wine glass"],
  },
  {
    emoji: "🥃",
    name: "Whisky",
    category: "Comida & Bebida",
    keywords: ["tumbler glass", "whisky"],
  },
  {
    emoji: "🍸",
    name: "Coquetel",
    category: "Comida & Bebida",
    keywords: ["cocktail glass"],
  },
  {
    emoji: "🍹",
    name: "Drink tropical",
    category: "Comida & Bebida",
    keywords: ["tropical drink"],
  },
  {
    emoji: "🍾",
    name: "Champanhe",
    category: "Comida & Bebida",
    keywords: ["bottle with popping cork"],
  },
  {
    emoji: "🧊",
    name: "Gelo",
    category: "Comida & Bebida",
    keywords: ["ice cube"],
  },
  {
    emoji: "🥢",
    name: "Hashi",
    category: "Comida & Bebida",
    keywords: ["chopsticks"],
  },

  // Atividades
  {
    emoji: "⚽",
    name: "Futebol",
    category: "Atividades",
    keywords: ["soccer", "ball", "bola"],
  },
  {
    emoji: "🏀",
    name: "Basquete",
    category: "Atividades",
    keywords: ["basketball"],
  },
  {
    emoji: "🏈",
    name: "Futebol americano",
    category: "Atividades",
    keywords: ["football"],
  },
  {
    emoji: "⚾",
    name: "Beisebol",
    category: "Atividades",
    keywords: ["baseball"],
  },
  { emoji: "🎾", name: "Tênis", category: "Atividades", keywords: ["tennis"] },
  {
    emoji: "🏐",
    name: "Vôlei",
    category: "Atividades",
    keywords: ["volleyball"],
  },
  { emoji: "🏉", name: "Rugby", category: "Atividades", keywords: ["rugby"] },
  {
    emoji: "🎱",
    name: "Sinuca",
    category: "Atividades",
    keywords: ["billiards", "8ball"],
  },
  {
    emoji: "🏓",
    name: "Ping pong",
    category: "Atividades",
    keywords: ["ping pong"],
  },
  {
    emoji: "🏸",
    name: "Badminton",
    category: "Atividades",
    keywords: ["badminton"],
  },
  { emoji: "🥅", name: "Gol", category: "Atividades", keywords: ["goal net"] },
  { emoji: "⛳", name: "Golfe", category: "Atividades", keywords: ["golf"] },
  {
    emoji: "🏹",
    name: "Arco e flecha",
    category: "Atividades",
    keywords: ["archery"],
  },
  { emoji: "🎣", name: "Pesca", category: "Atividades", keywords: ["fishing"] },
  {
    emoji: "🤿",
    name: "Mergulho",
    category: "Atividades",
    keywords: ["diving mask"],
  },
  {
    emoji: "🛼",
    name: "Patins",
    category: "Atividades",
    keywords: ["roller skates", "patins"],
  },
  {
    emoji: "🛹",
    name: "Skate",
    category: "Atividades",
    keywords: ["skateboard"],
  },
  {
    emoji: "⛷",
    name: "Esqui",
    category: "Atividades",
    keywords: ["skier"],
  },
  {
    emoji: "🏂",
    name: "Snowboard",
    category: "Atividades",
    keywords: ["snowboarder"],
  },
  {
    emoji: "🏋️",
    name: "Musculação",
    category: "Atividades",
    keywords: ["weight lifter", "gym", "academia"],
  },
  {
    emoji: "🚴",
    name: "Ciclismo",
    category: "Atividades",
    keywords: ["bicyclist", "bike"],
  },
  {
    emoji: "🏆",
    name: "Troféu",
    category: "Atividades",
    keywords: ["trophy", "win", "ganhar"],
  },
  {
    emoji: "🥇",
    name: "Medalha de ouro",
    category: "Atividades",
    keywords: ["1st place medal"],
  },
  {
    emoji: "🥈",
    name: "Medalha de prata",
    category: "Atividades",
    keywords: ["2nd place medal"],
  },
  {
    emoji: "🥉",
    name: "Medalha de bronze",
    category: "Atividades",
    keywords: ["3rd place medal"],
  },
  {
    emoji: "🎗",
    name: "Fita",
    category: "Atividades",
    keywords: ["reminder ribbon"],
  },
  {
    emoji: "🎟",
    name: "Ticket",
    category: "Atividades",
    keywords: ["admission tickets"],
  },
  {
    emoji: "🎫",
    name: "Ingresso",
    category: "Atividades",
    keywords: ["ticket"],
  },
  {
    emoji: "🎭",
    name: "Teatro",
    category: "Atividades",
    keywords: ["performing arts", "theater"],
  },
  {
    emoji: "🎨",
    name: "Pintura",
    category: "Atividades",
    keywords: ["artist palette", "art", "arte"],
  },
  {
    emoji: "🎬",
    name: "Cinema",
    category: "Atividades",
    keywords: ["clapper board", "movie"],
  },
  {
    emoji: "🎤",
    name: "Microfone",
    category: "Atividades",
    keywords: ["microphone", "sing", "cantar"],
  },
  {
    emoji: "🎧",
    name: "Fones de ouvido",
    category: "Atividades",
    keywords: ["headphone", "music", "música"],
  },
  {
    emoji: "🎸",
    name: "Guitarra",
    category: "Atividades",
    keywords: ["guitar", "music"],
  },
  {
    emoji: "🎹",
    name: "Teclado",
    category: "Atividades",
    keywords: ["musical keyboard", "piano"],
  },
  {
    emoji: "🎺",
    name: "Trompete",
    category: "Atividades",
    keywords: ["trumpet"],
  },
  {
    emoji: "🎻",
    name: "Violino",
    category: "Atividades",
    keywords: ["violin"],
  },
  { emoji: "🥁", name: "Tambor", category: "Atividades", keywords: ["drum"] },
  {
    emoji: "🎮",
    name: "Videogame",
    category: "Atividades",
    keywords: ["video game", "play", "jogar"],
  },
  {
    emoji: "🕹",
    name: "Joystick",
    category: "Atividades",
    keywords: ["joystick"],
  },
  {
    emoji: "🎰",
    name: "Caça-níquel",
    category: "Atividades",
    keywords: ["slot machine"],
  },
  {
    emoji: "🎲",
    name: "Dado",
    category: "Atividades",
    keywords: ["game die", "dice"],
  },
  {
    emoji: "🧩",
    name: "Quebra-cabeça",
    category: "Atividades",
    keywords: ["puzzle piece"],
  },
  {
    emoji: "🧸",
    name: "Ursinho",
    category: "Atividades",
    keywords: ["teddy bear"],
  },
  {
    emoji: "♟",
    name: "Xadrez",
    category: "Atividades",
    keywords: ["chess pawn"],
  },

  // Viagem & Lugares
  {
    emoji: "🚗",
    name: "Carro",
    category: "Viagem & Lugares",
    keywords: ["automobile", "car"],
  },
  {
    emoji: "🚕",
    name: "Táxi",
    category: "Viagem & Lugares",
    keywords: ["taxi"],
  },
  { emoji: "🚙", name: "SUV", category: "Viagem & Lugares", keywords: ["suv"] },
  {
    emoji: "🚌",
    name: "Ônibus",
    category: "Viagem & Lugares",
    keywords: ["bus"],
  },
  {
    emoji: "🏎",
    name: "Carro de corrida",
    category: "Viagem & Lugares",
    keywords: ["racing car"],
  },
  {
    emoji: "🚓",
    name: "Carro de polícia",
    category: "Viagem & Lugares",
    keywords: ["police car"],
  },
  {
    emoji: "🚑",
    name: "Ambulância",
    category: "Viagem & Lugares",
    keywords: ["ambulance"],
  },
  {
    emoji: "🚒",
    name: "Bombeiros",
    category: "Viagem & Lugares",
    keywords: ["fire engine"],
  },
  {
    emoji: "🚐",
    name: "Van",
    category: "Viagem & Lugares",
    keywords: ["minibus"],
  },
  {
    emoji: "🚚",
    name: "Caminhão",
    category: "Viagem & Lugares",
    keywords: ["delivery truck"],
  },
  {
    emoji: "🚛",
    name: "Caminhão articulado",
    category: "Viagem & Lugares",
    keywords: ["articulated lorry"],
  },
  {
    emoji: "🚜",
    name: "Trator",
    category: "Viagem & Lugares",
    keywords: ["tractor"],
  },
  {
    emoji: "🏍",
    name: "Moto",
    category: "Viagem & Lugares",
    keywords: ["motorcycle"],
  },
  {
    emoji: "🚲",
    name: "Bicicleta",
    category: "Viagem & Lugares",
    keywords: ["bicycle"],
  },
  {
    emoji: "🛵",
    name: "Scooter",
    category: "Viagem & Lugares",
    keywords: ["scooter"],
  },
  {
    emoji: "🛺",
    name: "Tuk tuk",
    category: "Viagem & Lugares",
    keywords: ["auto rickshaw"],
  },
  {
    emoji: "🚨",
    name: "Sirene",
    category: "Viagem & Lugares",
    keywords: ["police car light"],
  },
  {
    emoji: "🛣",
    name: "Estrada",
    category: "Viagem & Lugares",
    keywords: ["motorway"],
  },
  {
    emoji: "🛤",
    name: "Trilhos",
    category: "Viagem & Lugares",
    keywords: ["railway track"],
  },
  {
    emoji: "⛽",
    name: "Posto",
    category: "Viagem & Lugares",
    keywords: ["fuel pump"],
  },
  {
    emoji: "🛞",
    name: "Roda",
    category: "Viagem & Lugares",
    keywords: ["wheel"],
  },
  {
    emoji: "🅿️",
    name: "Estacionamento",
    category: "Viagem & Lugares",
    keywords: ["parking"],
  },
  {
    emoji: "⛵",
    name: "Veleiro",
    category: "Viagem & Lugares",
    keywords: ["sailboat"],
  },
  {
    emoji: "🚤",
    name: "Lancha",
    category: "Viagem & Lugares",
    keywords: ["speedboat"],
  },
  {
    emoji: "🛳",
    name: "Navio",
    category: "Viagem & Lugares",
    keywords: ["passenger ship"],
  },
  {
    emoji: "⛴",
    name: "Balsa",
    category: "Viagem & Lugares",
    keywords: ["ferry"],
  },
  {
    emoji: "🚢",
    name: "Navio cargueiro",
    category: "Viagem & Lugares",
    keywords: ["ship"],
  },
  {
    emoji: "✈️",
    name: "Avião",
    category: "Viagem & Lugares",
    keywords: ["airplane", "flight"],
  },
  {
    emoji: "🛫",
    name: "Decolagem",
    category: "Viagem & Lugares",
    keywords: ["airplane departure"],
  },
  {
    emoji: "🛬",
    name: "Pouso",
    category: "Viagem & Lugares",
    keywords: ["airplane arrival"],
  },
  {
    emoji: "🚁",
    name: "Helicóptero",
    category: "Viagem & Lugares",
    keywords: ["helicopter"],
  },
  {
    emoji: "🚀",
    name: "Foguete",
    category: "Viagem & Lugares",
    keywords: ["rocket", "space"],
  },
  {
    emoji: "🛸",
    name: "OVNI",
    category: "Viagem & Lugares",
    keywords: ["ufo"],
  },
  {
    emoji: "🛰",
    name: "Satélite",
    category: "Viagem & Lugares",
    keywords: ["satellite"],
  },
  {
    emoji: "🗼",
    name: "Torre de Tóquio",
    category: "Viagem & Lugares",
    keywords: ["tokyo tower"],
  },
  {
    emoji: "🗽",
    name: "Estátua da Liberdade",
    category: "Viagem & Lugares",
    keywords: ["statue of liberty"],
  },
  {
    emoji: "🗾",
    name: "Mapa do Japão",
    category: "Viagem & Lugares",
    keywords: ["map of japan"],
  },
  {
    emoji: "🗿",
    name: "Moai",
    category: "Viagem & Lugares",
    keywords: ["moai"],
  },
  {
    emoji: "🏠",
    name: "Casa",
    category: "Viagem & Lugares",
    keywords: ["house"],
  },
  {
    emoji: "🏡",
    name: "Casa com jardim",
    category: "Viagem & Lugares",
    keywords: ["house with garden"],
  },
  {
    emoji: "🏢",
    name: "Escritório",
    category: "Viagem & Lugares",
    keywords: ["office building"],
  },
  {
    emoji: "🏣",
    name: "Correios",
    category: "Viagem & Lugares",
    keywords: ["post office"],
  },
  {
    emoji: "🏤",
    name: "Correios europeu",
    category: "Viagem & Lugares",
    keywords: ["european post office"],
  },
  {
    emoji: "🏥",
    name: "Hospital",
    category: "Viagem & Lugares",
    keywords: ["hospital"],
  },
  {
    emoji: "🏦",
    name: "Banco",
    category: "Viagem & Lugares",
    keywords: ["bank"],
  },
  {
    emoji: "🏨",
    name: "Hotel",
    category: "Viagem & Lugares",
    keywords: ["hotel"],
  },
  {
    emoji: "🏩",
    name: "Motel",
    category: "Viagem & Lugares",
    keywords: ["love hotel"],
  },
  {
    emoji: "🏪",
    name: "Conveniência",
    category: "Viagem & Lugares",
    keywords: ["convenience store"],
  },
  {
    emoji: "🏫",
    name: "Escola",
    category: "Viagem & Lugares",
    keywords: ["school"],
  },
  {
    emoji: "🏬",
    name: "Loja de departamentos",
    category: "Viagem & Lugares",
    keywords: ["department store"],
  },
  {
    emoji: "🏭",
    name: "Fábrica",
    category: "Viagem & Lugares",
    keywords: ["factory"],
  },
  {
    emoji: "🏰",
    name: "Castelo",
    category: "Viagem & Lugares",
    keywords: ["castle"],
  },
  {
    emoji: "🏯",
    name: "Castelo japonês",
    category: "Viagem & Lugares",
    keywords: ["japanese castle"],
  },
  {
    emoji: "💒",
    name: "Casamento",
    category: "Viagem & Lugares",
    keywords: ["wedding"],
  },
  {
    emoji: "⛪",
    name: "Igreja",
    category: "Viagem & Lugares",
    keywords: ["church"],
  },
  {
    emoji: "🕌",
    name: "Mesquita",
    category: "Viagem & Lugares",
    keywords: ["mosque"],
  },
  {
    emoji: "🕍",
    name: "Sinagoga",
    category: "Viagem & Lugares",
    keywords: ["synagogue"],
  },
  {
    emoji: "⛺",
    name: "Acampamento",
    category: "Viagem & Lugares",
    keywords: ["tent"],
  },
  {
    emoji: "🌃",
    name: "Noite estrelada",
    category: "Viagem & Lugares",
    keywords: ["night with stars"],
  },
  {
    emoji: "🏙",
    name: "Cidade",
    category: "Viagem & Lugares",
    keywords: ["cityscape"],
  },
  {
    emoji: "🌄",
    name: "Amanhecer",
    category: "Viagem & Lugares",
    keywords: ["sunrise over mountains"],
  },
  {
    emoji: "🌅",
    name: "Pôr do sol",
    category: "Viagem & Lugares",
    keywords: ["sunrise"],
  },
  {
    emoji: "🌆",
    name: "Cidade ao entardecer",
    category: "Viagem & Lugares",
    keywords: ["cityscape at dusk"],
  },
  {
    emoji: "🌇",
    name: "Pôr do sol na cidade",
    category: "Viagem & Lugares",
    keywords: ["sunset"],
  },
  {
    emoji: "🌉",
    name: "Ponte à noite",
    category: "Viagem & Lugares",
    keywords: ["bridge at night"],
  },
  {
    emoji: "🌌",
    name: "Via Láctea",
    category: "Viagem & Lugares",
    keywords: ["milky way"],
  },
  {
    emoji: "🎠",
    name: "Carrossel",
    category: "Viagem & Lugares",
    keywords: ["carousel horse"],
  },
  {
    emoji: "🎡",
    name: "Roda gigante",
    category: "Viagem & Lugares",
    keywords: ["ferris wheel"],
  },
  {
    emoji: "🎢",
    name: "Montanha russa",
    category: "Viagem & Lugares",
    keywords: ["roller coaster"],
  },

  {
    emoji: "🧶",
    name: "Novelo",
    category: "Objetos",
    keywords: ["yarn", "knitting", "tricô", "crochê"],
  },
  {
    emoji: "🧣",
    name: "Cachecol",
    category: "Objetos",
    keywords: ["scarf", "winter", "inverno"],
  },
  {
    emoji: "🧵",
    name: "Linha",
    category: "Objetos",
    keywords: ["thread", "sewing", "costura"],
  },
  {
    emoji: "🪡",
    name: "Agulha",
    category: "Objetos",
    keywords: ["needle", "sewing"],
  },
  {
    emoji: "👒",
    name: "Chapéu de sol",
    category: "Objetos",
    keywords: ["sun hat", "woman", "chapeu"],
  },
  {
    emoji: "🧤",
    name: "Luvas",
    category: "Objetos",
    keywords: ["gloves", "winter"],
  },
  {
    emoji: "👗",
    name: "Vestido",
    category: "Objetos",
    keywords: ["dress", "fashion"],
  },
  {
    emoji: "⌚",
    name: "Relógio",
    category: "Objetos",
    keywords: ["watch", "time"],
  },
  {
    emoji: "📱",
    name: "Celular",
    category: "Objetos",
    keywords: ["phone", "tech"],
  },
  {
    emoji: "💻",
    name: "Laptop",
    category: "Objetos",
    keywords: ["laptop", "computer"],
  },
  { emoji: "⌨️", name: "Teclado", category: "Objetos", keywords: ["keyboard"] },
  {
    emoji: "🖥",
    name: "Monitor",
    category: "Objetos",
    keywords: ["desktop computer"],
  },
  {
    emoji: "🖨",
    name: "Impressora",
    category: "Objetos",
    keywords: ["printer"],
  },
  {
    emoji: "🖱",
    name: "Mouse",
    category: "Objetos",
    keywords: ["computer mouse"],
  },
  { emoji: "📷", name: "Câmera", category: "Objetos", keywords: ["camera"] },
  {
    emoji: "📸",
    name: "Câmera com flash",
    category: "Objetos",
    keywords: ["camera with flash"],
  },
  {
    emoji: "📹",
    name: "Filmadora",
    category: "Objetos",
    keywords: ["video camera"],
  },
  { emoji: "📺", name: "TV", category: "Objetos", keywords: ["television"] },
  { emoji: "📻", name: "Rádio", category: "Objetos", keywords: ["radio"] },
  { emoji: "🔋", name: "Bateria", category: "Objetos", keywords: ["battery"] },
  {
    emoji: "🔌",
    name: "Tomada",
    category: "Objetos",
    keywords: ["electric plug"],
  },
  {
    emoji: "💡",
    name: "Lâmpada",
    category: "Objetos",
    keywords: ["bulb", "idea", "idéia"],
  },
  {
    emoji: "🔦",
    name: "Lanterna",
    category: "Objetos",
    keywords: ["flashlight"],
  },
  { emoji: "🕯", name: "Vela", category: "Objetos", keywords: ["candle"] },
  {
    emoji: "🗑",
    name: "Lixeira",
    category: "Objetos",
    keywords: ["wastebasket"],
  },
  {
    emoji: "💸",
    name: "Dinheiro voando",
    category: "Objetos",
    keywords: ["money with wings"],
  },
  {
    emoji: "💵",
    name: "Dólar",
    category: "Objetos",
    keywords: ["dollar bill"],
  },
  { emoji: "💴", name: "Iene", category: "Objetos", keywords: ["yen bill"] },
  { emoji: "💶", name: "Euro", category: "Objetos", keywords: ["euro bill"] },
  { emoji: "💷", name: "Libra", category: "Objetos", keywords: ["pound bill"] },
  {
    emoji: "💰",
    name: "Saco de dinheiro",
    category: "Objetos",
    keywords: ["money bag"],
  },
  {
    emoji: "💳",
    name: "Cartão de crédito",
    category: "Objetos",
    keywords: ["credit card"],
  },
  {
    emoji: "💎",
    name: "Diamante",
    category: "Objetos",
    keywords: ["gem stone", "diamond"],
  },
  {
    emoji: "⚖️",
    name: "Balança",
    category: "Objetos",
    keywords: ["balance scale", "justice"],
  },
  { emoji: "🔨", name: "Martelo", category: "Objetos", keywords: ["hammer"] },
  { emoji: "🪓", name: "Machado", category: "Objetos", keywords: ["axe"] },
  {
    emoji: "🔧",
    name: "Chave de fenda",
    category: "Objetos",
    keywords: ["wrench"],
  },
  {
    emoji: "🪛",
    name: "Chave de fenda",
    category: "Objetos",
    keywords: ["screwdriver"],
  },
  {
    emoji: "🔩",
    name: "Parafuso",
    category: "Objetos",
    keywords: ["nut and bolt"],
  },
  { emoji: "⚙️", name: "Engrenagem", category: "Objetos", keywords: ["gear"] },
  {
    emoji: "🧱",
    name: "Tijolo",
    category: "Objetos",
    keywords: ["brick"],
  },
  {
    emoji: "⛓",
    name: "Corrente",
    category: "Objetos",
    keywords: ["chains"],
  },
  {
    emoji: "🧰",
    name: "Caixa de ferramentas",
    category: "Objetos",
    keywords: ["toolbox"],
  },
  {
    emoji: "🧲",
    name: "Ímã",
    category: "Objetos",
    keywords: ["magnet"],
  },
  {
    emoji: "🧪",
    name: "Tubo de ensaio",
    category: "Objetos",
    keywords: ["test tube"],
  },
  {
    emoji: "🧫",
    name: "Placa de Petri",
    category: "Objetos",
    keywords: ["petri dish"],
  },
  {
    emoji: "🧬",
    name: "DNA",
    category: "Objetos",
    keywords: ["dna"],
  },
  {
    emoji: "🔬",
    name: "Microscópio",
    category: "Objetos",
    keywords: ["microscope"],
  },
  {
    emoji: "🔭",
    name: "Telescópio",
    category: "Objetos",
    keywords: ["telescope"],
  },
  {
    emoji: "📡",
    name: "Antena",
    category: "Objetos",
    keywords: ["satellite antenna"],
  },
  {
    emoji: "💉",
    name: "Seringa",
    category: "Objetos",
    keywords: ["syringe"],
  },
  {
    emoji: "💊",
    name: "Pílula",
    category: "Objetos",
    keywords: ["pill"],
  },
  {
    emoji: "🩹",
    name: "Curativo",
    category: "Objetos",
    keywords: ["adhesive bandage"],
  },
  {
    emoji: "🩺",
    name: "Estetoscópio",
    category: "Objetos",
    keywords: ["stethoscopes"],
  },
  {
    emoji: "🚪",
    name: "Porta",
    category: "Objetos",
    keywords: ["door"],
  },
  {
    emoji: "🪞",
    name: "Espelho",
    category: "Objetos",
    keywords: ["mirror"],
  },
  {
    emoji: "🪟",
    name: "Janela",
    category: "Objetos",
    keywords: ["window"],
  },
  {
    emoji: "🛏",
    name: "Cama",
    category: "Objetos",
    keywords: ["bed"],
  },
  {
    emoji: "🛋",
    name: "Sofá",
    category: "Objetos",
    keywords: ["couch and lamp"],
  },
  {
    emoji: "🪑",
    name: "Cadeira",
    category: "Objetos",
    keywords: ["chair"],
  },
  {
    emoji: "🚽",
    name: "Vaso sanitário",
    category: "Objetos",
    keywords: ["toilet"],
  },
  {
    emoji: "🪠",
    name: "Desentupidor",
    category: "Objetos",
    keywords: ["plunger"],
  },
  {
    emoji: "🚿",
    name: "Chuveiro",
    category: "Objetos",
    keywords: ["shower"],
  },
  {
    emoji: "🛀",
    name: "Banho",
    category: "Objetos",
    keywords: ["bathtub"],
  },
  {
    emoji: "🧼",
    name: "Sabonete",
    category: "Objetos",
    keywords: ["soap"],
  },
  {
    emoji: "🪥",
    name: "Escova de dentes",
    category: "Objetos",
    keywords: ["toothbrush"],
  },
  {
    emoji: "🪒",
    name: "Barbeador",
    category: "Objetos",
    keywords: ["razor"],
  },
  {
    emoji: "🧺",
    name: "Cesta",
    category: "Objetos",
    keywords: ["basket"],
  },
  {
    emoji: "🧻",
    name: "Papel higiênico",
    category: "Objetos",
    keywords: ["roll of paper"],
  },
  {
    emoji: "🧴",
    name: "Loção",
    category: "Objetos",
    keywords: ["lotion bottle"],
  },
  {
    emoji: "🧽",
    name: "Esponja",
    category: "Objetos",
    keywords: ["sponge"],
  },
  {
    emoji: "🧹",
    name: "Vassoura",
    category: "Objetos",
    keywords: ["broom"],
  },
  {
    emoji: "🪣",
    name: "Balde",
    category: "Objetos",
    keywords: ["bucket"],
  },
  {
    emoji: "🧷",
    name: "Alfinete",
    category: "Objetos",
    keywords: ["safety pin"],
  },
  {
    emoji: "🪮",
    name: "Pente",
    category: "Objetos",
    keywords: ["hair pick"],
  },
  {
    emoji: "🎒",
    name: "Mochila",
    category: "Objetos",
    keywords: ["backpack"],
  },
  {
    emoji: "🎓",
    name: "Formatura",
    category: "Objetos",
    keywords: ["graduation cap", "chapeu"],
  },
  {
    emoji: "🎩",
    name: "Cartola",
    category: "Objetos",
    keywords: ["top hat", "chapeu"],
  },
  {
    emoji: "👟",
    name: "Tênis",
    category: "Objetos",
    keywords: ["running shoe"],
  },
  {
    emoji: "👞",
    name: "Sapato",
    category: "Objetos",
    keywords: ["shoe"],
  },
  {
    emoji: "👠",
    name: "Salto alto",
    category: "Objetos",
    keywords: ["high-heeled shoe"],
  },
  {
    emoji: "👡",
    name: "Sandália",
    category: "Objetos",
    keywords: ["sandal"],
  },
  {
    emoji: "👢",
    name: "Bota",
    category: "Objetos",
    keywords: ["boot"],
  },
  {
    emoji: "👑",
    name: "Coroa",
    category: "Objetos",
    keywords: ["crown"],
  },
  {
    emoji: "👛",
    name: "Bolsa",
    category: "Objetos",
    keywords: ["purse"],
  },
  {
    emoji: "👜",
    name: "Bolsa de mão",
    category: "Objetos",
    keywords: ["handbag"],
  },
  {
    emoji: "👝",
    name: "Clutch",
    category: "Objetos",
    keywords: ["clutch bag"],
  },
  {
    emoji: "💼",
    name: "Maleta",
    category: "Objetos",
    keywords: ["briefcase"],
  },
  {
    emoji: "👓",
    name: "Óculos",
    category: "Objetos",
    keywords: ["glasses"],
  },
  {
    emoji: "🕶",
    name: "Óculos escuros",
    category: "Objetos",
    keywords: ["sunglasses"],
  },
  {
    emoji: "💍",
    name: "Anel",
    category: "Objetos",
    keywords: ["ring"],
  },
  {
    emoji: "💄",
    name: "Batom",
    category: "Objetos",
    keywords: ["lipstick"],
  },
  {
    emoji: "🌂",
    name: "Guarda-chuva",
    category: "Objetos",
    keywords: ["umbrella"],
  },

  // Símbolos
  {
    emoji: "❤️",
    name: "Coração vermelho",
    category: "Símbolos",
    keywords: ["heart", "love", "amor"],
  },
  {
    emoji: "🩷",
    name: "Coração rosa",
    category: "Símbolos",
    keywords: ["pink heart", "love"],
  },
  {
    emoji: "🧡",
    name: "Coração laranja",
    category: "Símbolos",
    keywords: ["orange heart"],
  },
  {
    emoji: "💛",
    name: "Coração amarelo",
    category: "Símbolos",
    keywords: ["yellow heart"],
  },
  {
    emoji: "💚",
    name: "Coração verde",
    category: "Símbolos",
    keywords: ["green heart"],
  },
  {
    emoji: "💙",
    name: "Coração azul",
    category: "Símbolos",
    keywords: ["blue heart"],
  },
  {
    emoji: "💜",
    name: "Coração roxo",
    category: "Símbolos",
    keywords: ["purple heart"],
  },
  {
    emoji: "🖤",
    name: "Coração preto",
    category: "Símbolos",
    keywords: ["black heart"],
  },
  {
    emoji: "🩶",
    name: "Coração cinza",
    category: "Símbolos",
    keywords: ["grey heart"],
  },
  {
    emoji: "🤍",
    name: "Coração branco",
    category: "Símbolos",
    keywords: ["white heart"],
  },
  {
    emoji: "🤎",
    name: "Coração marrom",
    category: "Símbolos",
    keywords: ["brown heart"],
  },
  {
    emoji: "💔",
    name: "Coração partido",
    category: "Símbolos",
    keywords: ["broken heart"],
  },
  {
    emoji: "💕",
    name: "Dois corações",
    category: "Símbolos",
    keywords: ["two hearts"],
  },
  {
    emoji: "💞",
    name: "Corações giratórios",
    category: "Símbolos",
    keywords: ["revolving hearts"],
  },
  {
    emoji: "💓",
    name: "Coração batendo",
    category: "Símbolos",
    keywords: ["beating heart"],
  },
  {
    emoji: "💗",
    name: "Coração crescendo",
    category: "Símbolos",
    keywords: ["growing heart"],
  },
  {
    emoji: "💖",
    name: "Coração brilhante",
    category: "Símbolos",
    keywords: ["sparkling heart"],
  },
  {
    emoji: "💘",
    name: "Cupido",
    category: "Símbolos",
    keywords: ["heart with arrow"],
  },
  {
    emoji: "💝",
    name: "Coração com laço",
    category: "Símbolos",
    keywords: ["heart with ribbon"],
  },
  {
    emoji: "☮️",
    name: "Paz",
    category: "Símbolos",
    keywords: ["peace symbol"],
  },
  {
    emoji: "✝️",
    name: "Cruz",
    category: "Símbolos",
    keywords: ["latin cross"],
  },
  {
    emoji: "☪️",
    name: "Estrela e crescente",
    category: "Símbolos",
    keywords: ["star and crescent"],
  },
  { emoji: "🕉", name: "Om", category: "Símbolos", keywords: ["om"] },
  {
    emoji: "☸️",
    name: "Roda do dharma",
    category: "Símbolos",
    keywords: ["wheel of dharma"],
  },
  {
    emoji: "✡️",
    name: "Estrela de Davi",
    category: "Símbolos",
    keywords: ["star of david"],
  },
  {
    emoji: "🔯",
    name: "Estrela de seis pontas",
    category: "Símbolos",
    keywords: ["six pointed star with dot"],
  },
  { emoji: "🕎", name: "Menorá", category: "Símbolos", keywords: ["menorah"] },
  {
    emoji: "☯️",
    name: "Yin Yang",
    category: "Símbolos",
    keywords: ["yin yang"],
  },
  {
    emoji: "☦️",
    name: "Cruz ortodoxa",
    category: "Símbolos",
    keywords: ["orthodox cross"],
  },
  { emoji: "♈", name: "Áries", category: "Símbolos", keywords: ["aries"] },
  { emoji: "♉", name: "Touro", category: "Símbolos", keywords: ["taurus"] },
  { emoji: "♊", name: "Gêmeos", category: "Símbolos", keywords: ["gemini"] },
  { emoji: "♋", name: "Câncer", category: "Símbolos", keywords: ["cancer"] },
  { emoji: "♌", name: "Leão", category: "Símbolos", keywords: ["leo"] },
  { emoji: "♍", name: "Virgem", category: "Símbolos", keywords: ["virgo"] },
  { emoji: "♎", name: "Libra", category: "Símbolos", keywords: ["libra"] },
  {
    emoji: "♏",
    name: "Escorpião",
    category: "Símbolos",
    keywords: ["scorpio"],
  },
  {
    emoji: "♐",
    name: "Sagitário",
    category: "Símbolos",
    keywords: ["sagittarius"],
  },
  {
    emoji: "♑",
    name: "Capricórnio",
    category: "Símbolos",
    keywords: ["capricorn"],
  },
  {
    emoji: "♒",
    name: "Aquário",
    category: "Símbolos",
    keywords: ["aquarius"],
  },
  { emoji: "♓", name: "Peixes", category: "Símbolos", keywords: ["pisces"] },
  { emoji: "🆔", name: "ID", category: "Símbolos", keywords: ["id button"] },
  {
    emoji: "⚛️",
    name: "Átomo",
    category: "Símbolos",
    keywords: ["atom symbol"],
  },
  {
    emoji: "☢️",
    name: "Radioativo",
    category: "Símbolos",
    keywords: ["radioactive"],
  },
  {
    emoji: "☣️",
    name: "Risco biológico",
    category: "Símbolos",
    keywords: ["biohazard"],
  },
  {
    emoji: "📴",
    name: "Desligado",
    category: "Símbolos",
    keywords: ["mobile phone off"],
  },
  {
    emoji: "📳",
    name: "Vibrar",
    category: "Símbolos",
    keywords: ["vibration mode"],
  },
  {
    emoji: "🈶",
    name: "Não gratuito",
    category: "Símbolos",
    keywords: ["japanese not free of charge button"],
  },
  {
    emoji: "🈚",
    name: "Gratuito",
    category: "Símbolos",
    keywords: ["japanese free of charge button"],
  },
  {
    emoji: "🈺",
    name: "Aberto",
    category: "Símbolos",
    keywords: ["japanese open for business button"],
  },
  {
    emoji: "🈷️",
    name: "Mensal",
    category: "Símbolos",
    keywords: ["japanese monthly amount button"],
  },
  {
    emoji: "✴️",
    name: "Estrela de oito pontas",
    category: "Símbolos",
    keywords: ["eight pointed star"],
  },
  {
    emoji: "🆚",
    name: "Versus",
    category: "Símbolos",
    keywords: ["vs button"],
  },
  {
    emoji: "㊙️",
    name: "Segredo",
    category: "Símbolos",
    keywords: ["japanese secret button"],
  },
  {
    emoji: "㊗️",
    name: "Parabéns",
    category: "Símbolos",
    keywords: ["japanese congratulations button"],
  },
  {
    emoji: "🈴",
    name: "Aprovado",
    category: "Símbolos",
    keywords: ["japanese passing grade button"],
  },
  {
    emoji: "🈵",
    name: "Cheio",
    category: "Símbolos",
    keywords: ["japanese no vacancy button"],
  },
  {
    emoji: "🈹",
    name: "Desconto",
    category: "Símbolos",
    keywords: ["japanese discount button"],
  },
  {
    emoji: "🈲",
    name: "Proibido",
    category: "Símbolos",
    keywords: ["japanese prohibited button"],
  },
  {
    emoji: "🅰️",
    name: "Tipo A",
    category: "Símbolos",
    keywords: ["a button blood type"],
  },
  {
    emoji: "🅱️",
    name: "Tipo B",
    category: "Símbolos",
    keywords: ["b button blood type"],
  },
  {
    emoji: "AB",
    name: "Tipo AB",
    category: "Símbolos",
    keywords: ["ab button blood type"],
  },
  {
    emoji: "🆑",
    name: "Limpar",
    category: "Símbolos",
    keywords: ["cl button"],
  },
  {
    emoji: "🅾️",
    name: "Tipo O",
    category: "Símbolos",
    keywords: ["o button blood type"],
  },
  { emoji: "🆘", name: "SOS", category: "Símbolos", keywords: ["sos button"] },
  { emoji: "❌", name: "X", category: "Símbolos", keywords: ["cross mark"] },
  { emoji: "⭕", name: "Círculo", category: "Símbolos", keywords: ["circle"] },
  { emoji: "🛑", name: "Pare", category: "Símbolos", keywords: ["stop sign"] },
  {
    emoji: "⛔",
    name: "Proibido",
    category: "Símbolos",
    keywords: ["no entry"],
  },
  {
    emoji: "📛",
    name: "Crachá",
    category: "Símbolos",
    keywords: ["name badge"],
  },
  {
    emoji: "🚫",
    name: "Proibido",
    category: "Símbolos",
    keywords: ["prohibited"],
  },
  {
    emoji: "💯",
    name: "100",
    category: "Símbolos",
    keywords: ["hundred points", "top", "perfeito"],
  },
  {
    emoji: "💢",
    name: "Raiva",
    category: "Símbolos",
    keywords: ["anger symbol"],
  },
  {
    emoji: "♨️",
    name: "Águas termais",
    category: "Símbolos",
    keywords: ["hot springs"],
  },
  {
    emoji: "🔞",
    name: "18+",
    category: "Símbolos",
    keywords: ["no one under eighteen"],
  },
  {
    emoji: "❗️",
    name: "Exclamação",
    category: "Símbolos",
    keywords: ["exclamation mark"],
  },
  {
    emoji: "❓",
    name: "Interrogação",
    category: "Símbolos",
    keywords: ["question mark"],
  },
  { emoji: "⚠️", name: "Aviso", category: "Símbolos", keywords: ["warning"] },
  {
    emoji: "♻️",
    name: "Reciclar",
    category: "Símbolos",
    keywords: ["recycling symbol"],
  },
  {
    emoji: "✅",
    name: "Check",
    category: "Símbolos",
    keywords: ["check mark button", "sucesso", "feito"],
  },
  { emoji: "🌀", name: "Ciclone", category: "Símbolos", keywords: ["cyclone"] },
  {
    emoji: "🌐",
    name: "Globo",
    category: "Símbolos",
    keywords: ["globe with meridians"],
  },
  { emoji: "Ⓜ️", name: "M", category: "Símbolos", keywords: ["circled m"] },
  { emoji: "🏧", name: "ATM", category: "Símbolos", keywords: ["atm sign"] },
  {
    emoji: "♿",
    name: "Cadeira de rodas",
    category: "Símbolos",
    keywords: ["wheelchair symbol"],
  },
  {
    emoji: "🅿️",
    name: "Estacionamento",
    category: "Símbolos",
    keywords: ["p sign"],
  },
  {
    emoji: "🚻",
    name: "Banheiro",
    category: "Símbolos",
    keywords: ["restroom"],
  },
  {
    emoji: "📶",
    name: "Sinal",
    category: "Símbolos",
    keywords: ["antenna bars"],
  },
  {
    emoji: "ℹ️",
    name: "Informação",
    category: "Símbolos",
    keywords: ["information"],
  },
  { emoji: "🆗", name: "OK", category: "Símbolos", keywords: ["ok button"] },
  { emoji: "🆙", name: "UP!", category: "Símbolos", keywords: ["up! button"] },
  {
    emoji: "🆒",
    name: "COOL",
    category: "Símbolos",
    keywords: ["cool button"],
  },
  { emoji: "🆕", name: "NEW", category: "Símbolos", keywords: ["new button"] },
  {
    emoji: "🆓",
    name: "FREE",
    category: "Símbolos",
    keywords: ["free button"],
  },
  {
    emoji: "▶️",
    name: "Play",
    category: "Símbolos",
    keywords: ["play button"],
  },
  {
    emoji: "⏸",
    name: "Pause",
    category: "Símbolos",
    keywords: ["pause button"],
  },
  {
    emoji: "⏹",
    name: "Stop",
    category: "Símbolos",
    keywords: ["stop button"],
  },
  {
    emoji: "⏺",
    name: "Record",
    category: "Símbolos",
    keywords: ["record button"],
  },
  {
    emoji: "⏭",
    name: "Próximo",
    category: "Símbolos",
    keywords: ["next track button"],
  },
  {
    emoji: "⏮",
    name: "Anterior",
    category: "Símbolos",
    keywords: ["previous track button"],
  },
  {
    emoji: "⏩",
    name: "Avançar",
    category: "Símbolos",
    keywords: ["fast-forward button"],
  },
  {
    emoji: "⏪",
    name: "Retroceder",
    category: "Símbolos",
    keywords: ["fast reverse button"],
  },
  {
    emoji: "🔼",
    name: "Subir",
    category: "Símbolos",
    keywords: ["upwards button"],
  },
  {
    emoji: "🔽",
    name: "Descer",
    category: "Símbolos",
    keywords: ["downwards button"],
  },
  {
    emoji: "➡️",
    name: "Direita",
    category: "Símbolos",
    keywords: ["right arrow"],
  },
  {
    emoji: "⬅️",
    name: "Esquerda",
    category: "Símbolos",
    keywords: ["left arrow"],
  },
  { emoji: "⬆️", name: "Cima", category: "Símbolos", keywords: ["up arrow"] },
  {
    emoji: "⬇️",
    name: "Baixo",
    category: "Símbolos",
    keywords: ["down arrow"],
  },
  {
    emoji: "🔄",
    name: "Sincronizar",
    category: "Símbolos",
    keywords: ["counterclockwise arrows button"],
  },
  {
    emoji: "🔙",
    name: "Voltar",
    category: "Símbolos",
    keywords: ["back arrow"],
  },
  { emoji: "🔚", name: "Fim", category: "Símbolos", keywords: ["end arrow"] },
  {
    emoji: "🔛",
    name: "Ativado",
    category: "Símbolos",
    keywords: ["on! arrow"],
  },
  { emoji: "🔜", name: "Logo", category: "Símbolos", keywords: ["soon arrow"] },
  { emoji: "🔝", name: "Topo", category: "Símbolos", keywords: ["top arrow"] },
];
